import type {
  FilterChipOption,
  MediaLibraryItem,
  MediaLibrarySortKey,
  MediaLibraryTab,
  MediaStatusFilter,
  MediaTypeFilter,
} from "./media-library.types"

export const mediaLibraryTabOptions: FilterChipOption<MediaLibraryTab>[] = [
  { label: "All", value: "ALL" },
  { label: "Original", value: "ORIGINAL" },
  { label: "Editor Outputs", value: "EDITOR_OUTPUTS" },
  { label: "Long to Short", value: "LONG_TO_SHORT" },
]

export const mediaTypeFilterOptions: FilterChipOption<MediaTypeFilter>[] = [
  { label: "All", value: "ALL" },
  { label: "Video", value: "VIDEO" },
  { label: "Audio", value: "AUDIO" },
  { label: "Image", value: "IMAGE" },
  { label: "Transcript", value: "TRANSCRIPT" },
]

export const mediaStatusFilterOptions: FilterChipOption<MediaStatusFilter>[] = [
  { label: "All", value: "ALL" },
  { label: "Uploading", value: "UPLOADING" },
  { label: "Uploaded", value: "UPLOADED" },
  { label: "Failed", value: "FAILED" },
]

export const mediaSortOptions: FilterChipOption<MediaLibrarySortKey>[] = [
  { label: "Newest", value: "newest" },
  { label: "Oldest", value: "oldest" },
  { label: "Name", value: "name" },
  { label: "Duration", value: "duration" },
]

export const mediaLibraryItems: MediaLibraryItem[] = [
  {
    id: "media-library-1",
    title: "Quarterly Product Launch Keynote",
    originalFilename: "q2-launch-keynote-final.mp4",
    thumbnailUrl: null,
    duration: 1864,
    fileSizeBytes: 164_882_432,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-10T08:24:00.000Z",
    updatedAt: "2026-06-10T10:14:00.000Z",
    hasTranscript: true,
    hasChapters: true,
    hasClips: true,
    hasSubtitles: true,
    activeJobCount: 0,
    longToShortSourceId: "source_launch_keynote",
  },
  {
    id: "media-library-2",
    title: "Founder AMA Podcast Episode 42",
    originalFilename: "founder-ama-ep42.wav",
    thumbnailUrl: null,
    duration: 3246,
    fileSizeBytes: 91_204_608,
    mimeType: "audio/wav",
    type: "AUDIO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: null,
    height: null,
    createdAt: "2026-06-09T15:01:00.000Z",
    updatedAt: "2026-06-09T16:24:00.000Z",
    hasTranscript: true,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 1,
    longToShortSourceId: "source_founder_ama",
  },
  {
    id: "media-library-3",
    title: "Customer Story Interview - Retail",
    originalFilename: "customer-story-retail.mov",
    thumbnailUrl: null,
    duration: 972,
    fileSizeBytes: 246_315_008,
    mimeType: "video/quicktime",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 3840,
    height: 2160,
    createdAt: "2026-06-08T10:22:00.000Z",
    updatedAt: "2026-06-09T15:06:00.000Z",
    hasTranscript: true,
    hasChapters: true,
    hasClips: true,
    hasSubtitles: false,
    activeJobCount: 0,
    longToShortSourceId: "source_retail_story",
  },
  {
    id: "media-library-4",
    title: "Retail Campaign B-Roll Assembly",
    originalFilename: "retail-campaign-broll-v5.mp4",
    thumbnailUrl: null,
    duration: 802,
    fileSizeBytes: 121_635_840,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "FAILED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-08T04:50:00.000Z",
    updatedAt: "2026-06-08T05:37:00.000Z",
    hasTranscript: false,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
  {
    id: "media-library-5",
    title: "Summer Webinar Source Upload",
    originalFilename: "summer-webinar-intro.mp4",
    thumbnailUrl: null,
    duration: null,
    fileSizeBytes: 58_441_728,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADING",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-11T02:42:00.000Z",
    updatedAt: "2026-06-11T02:42:00.000Z",
    hasTranscript: false,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
    uploadProgress: 68,
  },
  {
    id: "media-library-6",
    title: "Vietnam Market Expansion Interview",
    originalFilename: "vn-market-expansion-interview.mp4",
    thumbnailUrl: null,
    duration: 1426,
    fileSizeBytes: 212_344_971,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-07T11:18:00.000Z",
    updatedAt: "2026-06-10T07:32:00.000Z",
    hasTranscript: true,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: true,
    activeJobCount: 2,
  },
  {
    id: "media-library-editor-1",
    title: "Launch Keynote Captioned Master",
    originalFilename: "launch-keynote-captioned-master.mp4",
    thumbnailUrl: null,
    duration: 1864,
    fileSizeBytes: 188_024_832,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "EDITOR_OUTPUT",
    status: "UPLOADED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-10T11:18:00.000Z",
    updatedAt: "2026-06-10T11:42:00.000Z",
    hasTranscript: true,
    hasChapters: true,
    hasClips: false,
    hasSubtitles: true,
    activeJobCount: 0,
  },
  {
    id: "media-library-editor-2",
    title: "Retail Story Transcript Export",
    originalFilename: "retail-story-transcript-v3.txt",
    thumbnailUrl: null,
    duration: null,
    fileSizeBytes: 184_320,
    mimeType: "text/plain",
    type: "TRANSCRIPT",
    libraryGroup: "EDITOR_OUTPUT",
    status: "UPLOADED",
    width: null,
    height: null,
    createdAt: "2026-06-09T15:10:00.000Z",
    updatedAt: "2026-06-09T15:12:00.000Z",
    hasTranscript: true,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
  {
    id: "media-library-editor-3",
    title: "Product Launch Thumbnail Set",
    originalFilename: "product-launch-thumbnail-cover.png",
    thumbnailUrl: null,
    duration: null,
    fileSizeBytes: 4_284_416,
    mimeType: "image/png",
    type: "IMAGE",
    libraryGroup: "EDITOR_OUTPUT",
    status: "UPLOADED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-10T12:22:00.000Z",
    updatedAt: "2026-06-10T12:22:00.000Z",
    hasTranscript: false,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
]

export const emptyMediaLibraryItems: MediaLibraryItem[] = []
