import type {
  FilterChipOption,
  MediaLibraryItem,
  MediaLibrarySortKey,
  MediaLibraryTab,
  MediaStatusFilter,
  MediaTypeFilter,
} from "./media-library.types"

export const mediaLibraryTabOptions: FilterChipOption<MediaLibraryTab>[] = [
  { label: "All", value: "ALL" },
  { label: "Original", value: "ORIGINAL" },
  { label: "Editor Outputs", value: "EDITOR_OUTPUTS" },
  { label: "Long to Short", value: "LONG_TO_SHORT" },
]

export const mediaTypeFilterOptions: FilterChipOption<MediaTypeFilter>[] = [
  { label: "All", value: "ALL" },
  { label: "Video", value: "VIDEO" },
  { label: "Audio", value: "AUDIO" },
  { label: "Image", value: "IMAGE" },
  { label: "Transcript", value: "TRANSCRIPT" },
]

export const mediaStatusFilterOptions: FilterChipOption<MediaStatusFilter>[] = [
  { label: "All", value: "ALL" },
  { label: "Uploading", value: "UPLOADING" },
  { label: "Uploaded", value: "UPLOADED" },
  { label: "Failed", value: "FAILED" },
]

export const mediaSortOptions: FilterChipOption<MediaLibrarySortKey>[] = [
  { label: "Newest", value: "newest" },
  { label: "Oldest", value: "oldest" },
  { label: "Name", value: "name" },
  { label: "Duration", value: "duration" },
]

export const mediaLibraryItems: MediaLibraryItem[] = [
  {
    id: "media-library-1",
    title: "Vertical Shorts Explainer",
    originalFilename:
      "YTDown_Shorts_Tai-Sao-Ong-Ta-Lai-Cat-Banh-Mot-Cach-Chi_Media_b8-wz8QqAFY_001_1080p.mp4",
    assetUrl:
      "/YTDown_Shorts_Tai-Sao-Ong-Ta-Lai-Cat-Banh-Mot-Cach-Chi_Media_b8-wz8QqAFY_001_1080p.mp4",
    thumbnailUrl: "/pexels-danil-lysov-175964361-12377231.jpg",
    duration: 28,
    fileSizeBytes: 11_006_041,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 1080,
    height: 1920,
    createdAt: "2026-06-10T08:24:00.000Z",
    updatedAt: "2026-06-10T10:14:00.000Z",
    hasTranscript: true,
    hasChapters: true,
    hasClips: true,
    hasSubtitles: true,
    activeJobCount: 0,
    longToShortSourceId: "source_launch_keynote",
  },
  {
    id: "media-library-2",
    title: "Vietnamese Audio Sample",
    originalFilename:
      "YTDown_Shorts_Gau-Khong-Lang-Phi-Nhu-Ban-Nghi_Media_307SMR9ERs_009_128k.mp3",
    assetUrl:
      "/YTDown_Shorts_Gau-Khong-Lang-Phi-Nhu-Ban-Nghi_Media_307SMR9ERs_009_128k.mp3",
    thumbnailUrl: null,
    duration: 55,
    fileSizeBytes: 1_108_400,
    mimeType: "audio/mpeg",
    type: "AUDIO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: null,
    height: null,
    createdAt: "2026-06-09T15:01:00.000Z",
    updatedAt: "2026-06-09T16:24:00.000Z",
    hasTranscript: true,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 1,
    longToShortSourceId: "source_founder_ama",
  },
  {
    id: "media-library-3",
    title: "Wildlife Horizontal Sample",
    originalFilename:
      "YTDown_YouTube_Wildlife-Windows-7-Sample-Video_Media_a3ICNMQW7Ok_001_720p.mp4",
    assetUrl:
      "/YTDown_YouTube_Wildlife-Windows-7-Sample-Video_Media_a3ICNMQW7Ok_001_720p.mp4",
    thumbnailUrl: "/pexels-francesco-ungaro-16771889.jpg",
    duration: 30,
    fileSizeBytes: 8_676_743,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 1280,
    height: 720,
    createdAt: "2026-06-08T10:22:00.000Z",
    updatedAt: "2026-06-09T15:06:00.000Z",
    hasTranscript: true,
    hasChapters: true,
    hasClips: true,
    hasSubtitles: false,
    activeJobCount: 0,
    longToShortSourceId: "source_retail_story",
  },
  {
    id: "media-library-4",
    title: "Vertical Portrait Still",
    originalFilename: "pexels-danil-lysov-175964361-12377231.jpg",
    assetUrl: "/pexels-danil-lysov-175964361-12377231.jpg",
    thumbnailUrl: "/pexels-danil-lysov-175964361-12377231.jpg",
    duration: null,
    fileSizeBytes: 1_660_641,
    mimeType: "image/jpeg",
    type: "IMAGE",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 1965,
    height: 3488,
    createdAt: "2026-06-08T04:50:00.000Z",
    updatedAt: "2026-06-08T05:37:00.000Z",
    hasTranscript: false,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
  {
    id: "media-library-5",
    title: "Horizontal Landscape Still",
    originalFilename: "pexels-francesco-ungaro-16771889.jpg",
    assetUrl: "/pexels-francesco-ungaro-16771889.jpg",
    thumbnailUrl: "/pexels-francesco-ungaro-16771889.jpg",
    duration: null,
    fileSizeBytes: 797_182,
    mimeType: "image/jpeg",
    type: "IMAGE",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: 4000,
    height: 3000,
    createdAt: "2026-06-11T02:42:00.000Z",
    updatedAt: "2026-06-11T02:42:00.000Z",
    hasTranscript: false,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
  {
    id: "media-library-6",
    title: "Mock Transcript Export",
    originalFilename: "mock-transcript-export.txt",
    assetUrl: "/mock-transcript-export.txt",
    thumbnailUrl: null,
    duration: null,
    fileSizeBytes: 484,
    mimeType: "text/plain",
    type: "TRANSCRIPT",
    libraryGroup: "ORIGINAL",
    status: "UPLOADED",
    width: null,
    height: null,
    createdAt: "2026-06-07T11:18:00.000Z",
    updatedAt: "2026-06-10T07:32:00.000Z",
    hasTranscript: true,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: true,
    activeJobCount: 2,
  },
  {
    id: "media-library-editor-1",
    title: "Launch Keynote Captioned Master",
    originalFilename: "launch-keynote-captioned-master.mp4",
    assetUrl:
      "/YTDown_YouTube_Wildlife-Windows-7-Sample-Video_Media_a3ICNMQW7Ok_001_720p.mp4",
    thumbnailUrl: "/pexels-francesco-ungaro-16771889.jpg",
    duration: 1864,
    fileSizeBytes: 188_024_832,
    mimeType: "video/mp4",
    type: "VIDEO",
    libraryGroup: "EDITOR_OUTPUT",
    status: "UPLOADED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-10T11:18:00.000Z",
    updatedAt: "2026-06-10T11:42:00.000Z",
    hasTranscript: true,
    hasChapters: true,
    hasClips: false,
    hasSubtitles: true,
    activeJobCount: 0,
  },
  {
    id: "media-library-editor-2",
    title: "Retail Story Transcript Export",
    originalFilename: "retail-story-transcript-v3.txt",
    assetUrl: "/mock-transcript-export.txt",
    thumbnailUrl: null,
    duration: null,
    fileSizeBytes: 184_320,
    mimeType: "text/plain",
    type: "TRANSCRIPT",
    libraryGroup: "EDITOR_OUTPUT",
    status: "UPLOADED",
    width: null,
    height: null,
    createdAt: "2026-06-09T15:10:00.000Z",
    updatedAt: "2026-06-09T15:12:00.000Z",
    hasTranscript: true,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
  {
    id: "media-library-editor-3",
    title: "Product Launch Thumbnail Set",
    originalFilename: "product-launch-thumbnail-cover.png",
    assetUrl: "/pexels-francesco-ungaro-16771889.jpg",
    thumbnailUrl: "/pexels-francesco-ungaro-16771889.jpg",
    duration: null,
    fileSizeBytes: 4_284_416,
    mimeType: "image/png",
    type: "IMAGE",
    libraryGroup: "EDITOR_OUTPUT",
    status: "UPLOADED",
    width: 1920,
    height: 1080,
    createdAt: "2026-06-10T12:22:00.000Z",
    updatedAt: "2026-06-10T12:22:00.000Z",
    hasTranscript: false,
    hasChapters: false,
    hasClips: false,
    hasSubtitles: false,
    activeJobCount: 0,
  },
]

export const emptyMediaLibraryItems: MediaLibraryItem[] = []
