ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'SHORT_CLIP_VIDEO';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'SHORT_CLIP_THUMBNAIL';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'SHORT_CLIP_SUBTITLE';
