import type {
  LongToShortCandidate,
  LongToShortClip,
  LongToShortJob,
  LongToShortSettings,
  LongToShortSource,
} from "./long-to-short.types"

export const longToShortSources: LongToShortSource[] = [
  {
    id: "source_launch_keynote",
    projectSlug: "project-launch-campaign",
    title: "Project Launch Campaign",
    sourceFileName: "launch-keynote-v3.mp4",
    type: "VIDEO",
    durationLabel: "31:04",
    transcriptStatus: "READY",
    chapterStatus: "READY",
    status: "READY",
  },
  {
    id: "source_founder_ama",
    projectSlug: "founder-ama",
    title: "Founder AMA",
    sourceFileName: "founder-ama-ep42.wav",
    type: "AUDIO",
    durationLabel: "54:06",
    transcriptStatus: "READY",
    chapterStatus: "MISSING",
    status: "PROCESSING",
  },
  {
    id: "source_retail_story",
    projectSlug: "retail-customer-story",
    title: "Retail Customer Story",
    sourceFileName: "retail-story-master.mov",
    type: "VIDEO",
    durationLabel: "16:12",
    transcriptStatus: "READY",
    chapterStatus: "READY",
    status: "READY",
  },
]

export const defaultLongToShortSettings: LongToShortSettings = {
  clipCount: 3,
  minDuration: 20,
  maxDuration: 45,
  aspectRatio: "9:16",
  platform: "TIKTOK",
  burnSubtitles: true,
}

export const longToShortJobsBySourceId: Record<string, LongToShortJob> = {
  source_launch_keynote: {
    sourceId: "source_launch_keynote",
    status: "RUNNING",
    progress: 62,
    currentStep: "Rendering vertical drafts from selected moments",
  },
  source_founder_ama: {
    sourceId: "source_founder_ama",
    status: "QUEUED",
    progress: 12,
    currentStep: "Waiting for chapter-aware candidate generation",
  },
  source_retail_story: {
    sourceId: "source_retail_story",
    status: "COMPLETED",
    progress: 100,
    currentStep: "Draft clips ready for review",
  },
}

export const longToShortCandidatesBySourceId: Record<string, LongToShortCandidate[]> = {
  source_launch_keynote: [
    {
      id: "candidate_launch_001",
      sourceId: "source_launch_keynote",
      sourceChapterLabel: "Why transcript quality matters",
      title: "Transcript before everything",
      caption: "Why transcript cleanup pays off before chapters and clips.",
      startTime: 12,
      endTime: 42,
      duration: 30,
      transcript:
        "The workflow starts with a clean transcript before anything downstream becomes useful.",
      reviewNotes: [
        "Strong opening line",
        "Self-contained idea",
        "Good short-form length",
      ],
      status: "SELECTED",
      aspectRatio: "9:16",
      platform: "TIKTOK",
      burnSubtitles: true,
      transcriptVersionLabel: "Transcript v4",
      isOutdated: true,
    },
    {
      id: "candidate_launch_002",
      sourceId: "source_launch_keynote",
      sourceChapterLabel: "Reusable content pipeline",
      title: "When clips stop drifting",
      caption: "The transcript keeps chapters and short clips aligned to the actual message.",
      startTime: 104,
      endTime: 138,
      duration: 34,
      transcript:
        "Once the wording is right, chaptering and clip selection stop drifting away from the actual message.",
      reviewNotes: [
        "Clear takeaway",
        "Ending lands cleanly",
        "Works well for vertical video",
      ],
      status: "RECOMMENDED",
      aspectRatio: "9:16",
      platform: "YOUTUBE_SHORTS",
      burnSubtitles: true,
      transcriptVersionLabel: "Transcript v4",
    },
    {
      id: "candidate_launch_003",
      sourceId: "source_launch_keynote",
      sourceChapterLabel: "Reusable content pipeline",
      title: "One upload, many outputs",
      caption: "How one source recording becomes chapters, clips, subtitles, and publish-ready assets.",
      startTime: 148,
      endTime: 190,
      duration: 42,
      transcript:
        "That gives the team something they can review, publish, and reuse without re-uploading the source video.",
      reviewNotes: [
        "Clear business value",
        "Useful standalone takeaway",
        "Needs tighter opening",
      ],
      status: "NEEDS_REVIEW",
      aspectRatio: "1:1",
      platform: "INSTAGRAM_REELS",
      burnSubtitles: false,
      transcriptVersionLabel: "Transcript v4",
    },
  ],
  source_founder_ama: [
    {
      id: "candidate_ama_001",
      sourceId: "source_founder_ama",
      title: "Why consistency wins",
      caption: "The point most creators miss when they judge content too early.",
      startTime: 84,
      endTime: 119,
      duration: 35,
      transcript:
        "Most channels do not fail because the topic is wrong. They fail because the team stops before the feedback loop has enough time to work.",
      reviewNotes: [
        "Strong lesson",
        "Clear emotional arc",
        "Needs chapter context later",
      ],
      status: "RECOMMENDED",
      aspectRatio: "9:16",
      platform: "TIKTOK",
      burnSubtitles: true,
      transcriptVersionLabel: "Transcript v2",
    },
  ],
  source_retail_story: [
    {
      id: "candidate_retail_001",
      sourceId: "source_retail_story",
      sourceChapterLabel: "Customer moment",
      title: "The turning point in onboarding",
      caption: "A short answer that lands fast without needing extra setup.",
      startTime: 56,
      endTime: 84,
      duration: 28,
      transcript:
        "The team finally trusted the workflow once onboarding stopped depending on handoffs between five different tools.",
      reviewNotes: [
        "Fast opening",
        "Easy to understand alone",
        "Clean closing sentence",
      ],
      status: "RECOMMENDED",
      aspectRatio: "9:16",
      platform: "INSTAGRAM_REELS",
      burnSubtitles: true,
      transcriptVersionLabel: "Transcript v3",
    },
  ],
}

export const longToShortClipsBySourceId: Record<string, LongToShortClip[]> = {
  source_launch_keynote: [
    {
      id: "clip_launch_001",
      sourceId: "source_launch_keynote",
      sourceCandidateId: "candidate_launch_001",
      title: "Transcript before everything",
      caption: "Why transcript cleanup pays off before chapters and clips.",
      startTime: 12,
      endTime: 42,
      duration: 30,
      status: "READY",
      aspectRatio: "9:16",
      platform: "TIKTOK",
      burnSubtitles: true,
      updatedAtLabel: "Updated 2h ago",
    },
    {
      id: "clip_launch_002",
      sourceId: "source_launch_keynote",
      sourceCandidateId: "candidate_launch_002",
      title: "When clips stop drifting",
      caption: "The transcript keeps chapters and short clips aligned to the actual message.",
      startTime: 104,
      endTime: 138,
      duration: 34,
      status: "DRAFT",
      aspectRatio: "9:16",
      platform: "YOUTUBE_SHORTS",
      burnSubtitles: true,
      updatedAtLabel: "Updated 18m ago",
    },
  ],
  source_founder_ama: [],
  source_retail_story: [
    {
      id: "clip_retail_001",
      sourceId: "source_retail_story",
      sourceCandidateId: "candidate_retail_001",
      title: "The turning point in onboarding",
      caption: "A short answer that lands fast without needing extra setup.",
      startTime: 56,
      endTime: 84,
      duration: 28,
      status: "READY",
      aspectRatio: "1:1",
      platform: "INSTAGRAM_REELS",
      burnSubtitles: true,
      updatedAtLabel: "Updated yesterday",
    },
  ],
}
