export const TIMELINE_ZOOM_MIN = 1
export const TIMELINE_ZOOM_MAX = 48
export const TIMELINE_BUTTON_ZOOM_MULTIPLIER = 1.25
export const TIMELINE_PINCH_ZOOM_SENSITIVITY = 0.004
export const TIMELINE_BASE_WIDTH = 980
export const TIMELINE_TARGET_TICK_WIDTH = 140
export const TIMELINE_SEGMENT_MIN_DURATION = 0.5
export const TIMELINE_DEFAULT_LANE_HEIGHT = 32
export const TIMELINE_VIDEO_LANE_HEIGHT = 64
export const TIMELINE_GRID_LABEL_WIDTH = 72

export const TIMELINE_MAJOR_INTERVALS = [
  5, 10, 15, 30, 60, 120, 180, 300, 600, 900, 1800,
] as const

export const TIMELINE_MIN_HEIGHT = 128
export const TIMELINE_MAX_HEIGHT = 420
export const TIMELINE_DEFAULT_HEIGHT = 168
export const TIMELINE_COLLAPSED_HEIGHT = 48
