import type {
  PublishAccountOption,
  PublishPlatform,
  PublishPlatformFilter,
  PublishSortKey,
  PublishSourceOption,
  PublishStatusFilter,
  PublishTask,
} from "./publishing.types"

export const publishStatusFilterOptions: {
  label: string
  value: PublishStatusFilter
}[] = [
  { label: "All", value: "ALL" },
  { label: "Drafts", value: "DRAFT" },
  { label: "Scheduled", value: "SCHEDULED" },
  { label: "Publishing", value: "PUBLISHING" },
  { label: "Published", value: "PUBLISHED" },
  { label: "Failed", value: "FAILED" },
]

export const publishPlatformFilterOptions: {
  label: string
  value: PublishPlatformFilter
}[] = [
  { label: "All", value: "ALL" },
  { label: "YouTube", value: "YOUTUBE" },
  { label: "TikTok", value: "TIKTOK" },
  { label: "Facebook", value: "FACEBOOK" },
  { label: "Instagram", value: "INSTAGRAM" },
]

export const publishSortOptions: {
  label: string
  value: PublishSortKey
}[] = [
  { label: "Newest", value: "newest" },
  { label: "Scheduled soon", value: "scheduledSoon" },
  { label: "Recently published", value: "recentlyPublished" },
]

export const publishPlatformLabels: Record<PublishPlatform, string> = {
  YOUTUBE: "YouTube",
  TIKTOK: "TikTok",
  FACEBOOK: "Facebook",
  INSTAGRAM: "Instagram",
}

export const publishAccountOptions: PublishAccountOption[] = [
  {
    id: "pa-youtube-1",
    platform: "YOUTUBE",
    accountName: "VidPilot Studio",
  },
  {
    id: "pa-youtube-2",
    platform: "YOUTUBE",
    accountName: "VidPilot Shorts",
  },
  {
    id: "pa-tiktok-1",
    platform: "TIKTOK",
    accountName: "vidpilot_creator",
  },
  {
    id: "pa-facebook-1",
    platform: "FACEBOOK",
    accountName: "VidPilot",
  },
  {
    id: "pa-facebook-2",
    platform: "FACEBOOK",
    accountName: "VidPilot Community",
  },
  {
    id: "pa-instagram-1",
    platform: "INSTAGRAM",
    accountName: "vidpilot.business",
  },
]

export const publishSourceOptions: PublishSourceOption[] = [
  {
    id: "source-1",
    sourceType: "SHORT_CLIP",
    mediaId: "media-library-1",
    shortClipId: "clip-launch-1",
    title: "Launch keynote: 30-second product reveal",
    meta: "Short clip from Quarterly Product Launch Keynote",
    thumbnailUrl: null,
    aspectRatio: "9:16",
    durationLabel: "0:31",
  },
  {
    id: "source-2",
    sourceType: "MEDIA",
    mediaId: "media-library-3",
    shortClipId: null,
    title: "Customer Story Interview - Retail",
    meta: "Source media with chapters and transcript",
    thumbnailUrl: null,
    aspectRatio: "16:9",
    durationLabel: "16:12",
  },
  {
    id: "source-3",
    sourceType: "SHORT_CLIP",
    mediaId: "media-library-5",
    shortClipId: "clip-webinar-2",
    title: "Webinar hook: workflow before and after",
    meta: "Short clip from Summer Webinar Source Upload",
    thumbnailUrl: null,
    aspectRatio: "9:16",
    durationLabel: "0:42",
  },
  {
    id: "source-4",
    sourceType: "MEDIA",
    mediaId: "media-library-2",
    shortClipId: null,
    title: "Founder AMA Podcast Episode 42",
    meta: "Audio source with transcript",
    thumbnailUrl: null,
    aspectRatio: "1:1",
    durationLabel: "54:06",
  },
]

export const publishTasksSeed: PublishTask[] = [
  {
    id: "publish-1",
    mediaId: "media-library-1",
    shortClipId: "clip-launch-1",
    sourceType: "SHORT_CLIP",
    thumbnailUrl: null,
    sourceTitle: "Launch keynote: 30-second product reveal",
    sourceMeta: "Short clip from Quarterly Product Launch Keynote",
    aspectRatio: "9:16",
    durationLabel: "0:31",
    platform: "TIKTOK",
    platformAccountName: "vidpilot_creator",
    title: "The fastest way to turn long videos into a launch sequence",
    caption:
      "One source keynote became chapters, clips, captions, and publish-ready posts in one workspace.",
    hashtags: ["#videoworkflow", "#contentops", "#aivideo"],
    status: "SCHEDULED",
    progress: null,
    scheduledAt: "2026-06-13T15:30:00.000Z",
    publishedAt: null,
    platformPostUrl: null,
    errorMessage: null,
    createdAt: "2026-06-12T09:12:00.000Z",
  },
  {
    id: "publish-2",
    mediaId: "media-library-3",
    shortClipId: null,
    sourceType: "MEDIA",
    thumbnailUrl: null,
    sourceTitle: "Customer Story Interview - Retail",
    sourceMeta: "Source media with transcript and chapters",
    aspectRatio: "16:9",
    durationLabel: "16:12",
    platform: "YOUTUBE",
    platformAccountName: "VidPilot Studio",
    title: "How a retail team plans a week of content from one interview",
    caption:
      "A customer story walkthrough with chapters, searchable transcript, and reusable clips.",
    hashtags: ["#customerstory", "#retail", "#contentstrategy"],
    status: "PUBLISHED",
    progress: null,
    scheduledAt: "2026-06-12T08:00:00.000Z",
    publishedAt: "2026-06-12T08:04:00.000Z",
    platformPostUrl: "https://youtube.com/watch?v=mock-retail-story",
    errorMessage: null,
    createdAt: "2026-06-11T11:24:00.000Z",
  },
  {
    id: "publish-3",
    mediaId: "media-library-5",
    shortClipId: "clip-webinar-2",
    sourceType: "SHORT_CLIP",
    thumbnailUrl: null,
    sourceTitle: "Webinar hook: workflow before and after",
    sourceMeta: "Short clip from Summer Webinar Source Upload",
    aspectRatio: "9:16",
    durationLabel: "0:42",
    platform: "INSTAGRAM",
    platformAccountName: "vidpilot.business",
    title: "Before and after: one upload, every output",
    caption:
      "A quick look at how source media turns into captions, chapters, and scheduled social posts.",
    hashtags: ["#creatorworkflow", "#reels", "#aicontent"],
    status: "PUBLISHING",
    progress: 68,
    scheduledAt: "2026-06-13T11:45:00.000Z",
    publishedAt: null,
    platformPostUrl: null,
    errorMessage: null,
    createdAt: "2026-06-13T10:02:00.000Z",
  },
  {
    id: "publish-4",
    mediaId: "media-library-2",
    shortClipId: null,
    sourceType: "MEDIA",
    thumbnailUrl: null,
    sourceTitle: "Founder AMA Podcast Episode 42",
    sourceMeta: "Audio source with transcript",
    aspectRatio: "1:1",
    durationLabel: "54:06",
    platform: "FACEBOOK",
    platformAccountName: "VidPilot",
    title: "Founder AMA: what creators need from AI tooling",
    caption:
      "A longer discussion about transcript-first creation and multi-platform publishing.",
    hashtags: ["#founderama", "#creatorstack"],
    status: "FAILED",
    progress: null,
    scheduledAt: "2026-06-11T13:00:00.000Z",
    publishedAt: null,
    platformPostUrl: null,
    errorMessage:
      "Facebook rejected the post because the connected page session needs to be refreshed.",
    createdAt: "2026-06-11T10:38:00.000Z",
  },
  {
    id: "publish-5",
    mediaId: "media-library-1",
    shortClipId: "clip-launch-2",
    sourceType: "SHORT_CLIP",
    thumbnailUrl: null,
    sourceTitle: "Launch keynote: chapter automation proof",
    sourceMeta: "Short clip from Quarterly Product Launch Keynote",
    aspectRatio: "9:16",
    durationLabel: "0:27",
    platform: "INSTAGRAM",
    platformAccountName: "vidpilot.business",
    title: null,
    caption:
      "Draft caption: show the moment where the source video becomes publishable assets.",
    hashtags: ["#videocreator", "#contentcalendar"],
    status: "DRAFT",
    progress: null,
    scheduledAt: null,
    publishedAt: null,
    platformPostUrl: null,
    errorMessage: null,
    createdAt: "2026-06-13T03:42:00.000Z",
  },
  {
    id: "publish-6",
    mediaId: "media-library-3",
    shortClipId: "clip-retail-1",
    sourceType: "SHORT_CLIP",
    thumbnailUrl: null,
    sourceTitle: "Retail interview: strongest customer quote",
    sourceMeta: "Short clip from Customer Story Interview - Retail",
    aspectRatio: "9:16",
    durationLabel: "0:35",
    platform: "TIKTOK",
    platformAccountName: "vidpilot_creator",
    title: "The customer quote worth turning into a clip",
    caption:
      "Pull the strongest quote from the transcript, then review it as a short-form draft.",
    hashtags: ["#customerquote", "#shortform", "#videoteam"],
    status: "SCHEDULED",
    progress: null,
    scheduledAt: "2026-06-14T09:15:00.000Z",
    publishedAt: null,
    platformPostUrl: null,
    errorMessage: null,
    createdAt: "2026-06-12T14:20:00.000Z",
  },
  {
    id: "publish-7",
    mediaId: "media-library-1",
    shortClipId: null,
    sourceType: "MEDIA",
    thumbnailUrl: null,
    sourceTitle: "Quarterly Product Launch Keynote",
    sourceMeta: "Full source media",
    aspectRatio: "16:9",
    durationLabel: "31:04",
    platform: "YOUTUBE",
    platformAccountName: "VidPilot Studio",
    title: "Quarterly Product Launch Keynote: chapters and demos",
    caption:
      "The full launch session with chapters, subtitles, and links to short clips.",
    hashtags: ["#productlaunch", "#keynote"],
    status: "SCHEDULED",
    progress: null,
    scheduledAt: "2026-06-15T16:00:00.000Z",
    publishedAt: null,
    platformPostUrl: null,
    errorMessage: null,
    createdAt: "2026-06-12T18:10:00.000Z",
  },
  {
    id: "publish-8",
    mediaId: "media-library-5",
    shortClipId: "clip-webinar-3",
    sourceType: "SHORT_CLIP",
    thumbnailUrl: null,
    sourceTitle: "Webinar answer: why transcript edits matter",
    sourceMeta: "Short clip from Summer Webinar Source Upload",
    aspectRatio: "9:16",
    durationLabel: "0:39",
    platform: "FACEBOOK",
    platformAccountName: "VidPilot",
    title: "Why transcript edits should update every downstream output",
    caption:
      "When the transcript is the source of truth, captions, chapters, and clips stay in sync.",
    hashtags: ["#transcripts", "#contentworkflow"],
    status: "PUBLISHED",
    progress: null,
    scheduledAt: "2026-06-10T07:30:00.000Z",
    publishedAt: "2026-06-10T07:33:00.000Z",
    platformPostUrl: "https://facebook.com/vidpilot/posts/mock-transcript-edits",
    errorMessage: null,
    createdAt: "2026-06-09T15:16:00.000Z",
  },
]
